import { FaGoogle, FaGithub } from "react-icons/fa";
import {
  Home,
  Users,
  LineChart,
  Mail,
  Workflow,
  Database,
  Palette,
  Rocket,
  Settings,
  Package,
  Files,
  LucideIcon,
  Loader2,
  Plus,
  Download,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Minus,
  X,
  Check,
  Upload,
  Save,
  Trash,
  Edit,
  Share,
  Bell,
  Info,
  AlertCircle,
  AlertTriangle,
  Circle,
  Square,
  Star,
  Heart,
  Bookmark,
  Clock,
  Calendar,
  MapPin,
  Phone,
  Monitor,
  Smartphone,
  Eye,
  FileText,
  FileCode,
  Copy,
  RefreshCw,
  Search,
  Filter,
  User,
  UserPlus,
  UserMinus,
  Users2,
  Folder,
  FolderOpen,
  File,
  Image,
  Video,
  Music,
  BookOpen,
  Zap,
  Lock,
  Unlock,
  Shield,
  Key,
  Globe,
  Wifi,
  Cloud,
  ExternalLink,
  Link,
  Unlink,
  Grid,
  List,
  Menu,
  MoreHorizontal,
  MoreVertical,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  ChevronsDown,
  Play,
  Pause,
  Square as StopIcon,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  Move,
  Layout,
  Sidebar,
  PanelLeft,
  PanelRight,
  Layers,
  Type,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Camera,
  DollarSign,
  TrendingUp,
  TrendingDown,
} from "lucide-react";

export type Icon = LucideIcon | React.ComponentType<any>;

export const Icons = {
  // Navigation & UI
  homeIcon: Home,
  usersIcon: Users,
  userIcon: User,
  userPlusIcon: UserPlus,
  userMinusIcon: UserMinus,
  users2Icon: Users2,
  settingsIcon: Settings,
  searchIcon: Search,
  filterIcon: Filter,
  menuIcon: Menu,
  moreHorizontalIcon: MoreHorizontal,
  moreVerticalIcon: MoreVertical,
  
  // Actions
  plusIcon: Plus,
  minusIcon: Minus,
  xIcon: X,
  checkIcon: Check,
  editIcon: Edit,
  trashIcon: Trash,
  saveIcon: Save,
  copyIcon: Copy,
  shareIcon: Share,
  downloadIcon: Download,
  uploadIcon: Upload,
  refreshCwIcon: RefreshCw,
  
  // Arrows & Directions
  arrowRightIcon: ArrowRight,
  arrowLeftIcon: ArrowLeft,
  arrowUpIcon: ArrowUp,
  arrowDownIcon: ArrowDown,
  chevronUpIcon: ChevronUp,
  chevronDownIcon: ChevronDown,
  chevronLeftIcon: ChevronLeft,
  chevronRightIcon: ChevronRight,
  chevronsUpIcon: ChevronsUp,
  chevronsDownIcon: ChevronsDown,
  
  // Status & Alerts
  bellIcon: Bell,
  infoIcon: Info,
  alertCircleIcon: AlertCircle,
  alertTriangleIcon: AlertTriangle,
  checkCircleIcon: Check,
  
  // Shapes & Basic
  circleIcon: Circle,
  squareIcon: Square,
  starIcon: Star,
  heartIcon: Heart,
  bookmarkIcon: Bookmark,
  
  // Time & Location
  clockIcon: Clock,
  calendarIcon: Calendar,
  mapPinIcon: MapPin,
  
  // Communication
  mailIcon: Mail,
  phoneIcon: Phone,
  
  // Devices
  monitorIcon: Monitor,
  smartphoneIcon: Smartphone,
  
  // Files & Folders
  folderIcon: Folder,
  folderOpenIcon: FolderOpen,
  fileIcon: File,
  filesIcon: Files,
  fileTextIcon: FileText,
  fileCodeIcon: FileCode,
  imageIcon: Image,
  videoIcon: Video,
  musicIcon: Music,
  
  // Media Controls
  playIcon: Play,
  pauseIcon: Pause,
  stopIcon: StopIcon,
  volume2Icon: Volume2,
  volumeXIcon: VolumeX,
  
  // Layout & View
  eyeIcon: Eye,
  gridIcon: Grid,
  listIcon: List,
  maximizeIcon: Maximize,
  minimizeIcon: Minimize,
  layoutIcon: Layout,
  sidebarIcon: Sidebar,
  panelLeftIcon: PanelLeft,
  panelRightIcon: PanelRight,
  layersIcon: Layers,
  
  // Text Formatting
  typeIcon: Type,
  boldIcon: Bold,
  italicIcon: Italic,
  underlineIcon: Underline,
  alignLeftIcon: AlignLeft,
  alignCenterIcon: AlignCenter,
  alignRightIcon: AlignRight,
  alignJustifyIcon: AlignJustify,
  
  // Business & Analytics
  lineChartIcon: LineChart,
  packageIcon: Package,
  workflowIcon: Workflow,
  databaseIcon: Database,
  rocketIcon: Rocket,
  
  // Security
  lockIcon: Lock,
  unlockIcon: Unlock,
  shieldIcon: Shield,
  keyIcon: Key,
  
  // Network & Cloud
  globeIcon: Globe,
  wifiIcon: Wifi,
  cloudIcon: Cloud,
  linkIcon: Link,
  unlinkIcon: Unlink,
  externalLinkIcon: ExternalLink,
  
  // Design & Development
  paletteIcon: Palette,
  zapIcon: Zap,
  bookOpenIcon: BookOpen,
  moveIcon: Move,
  rotateCcwIcon: RotateCcw,
  rotateCwIcon: RotateCw,
  
  // Loading & System
  spinnerIcon: Loader2,
  
  // Additional icons
  cameraIcon: Camera,
  dollarSignIcon: DollarSign,
  trendingUpIcon: TrendingUp,
  trendingDownIcon: TrendingDown,
  
  // Social & External
  gitHubIcon: FaGithub,
  googleIcon: FaGoogle,
} as const;

export type IconKeys = keyof typeof Icons;
