export interface PredefinedTheme {
  id: string;
  name: string;
  category: 'popular' | 'nature' | 'corporate' | 'creative' | 'monochrome' | 'specialty';
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    foreground: string;
  };
  lightModeConfig: Record<string, string>;
  darkModeConfig: Record<string, string>;
}

// Complete TweakCN Theme Collection - 40 Themes
export const PREDEFINED_THEMES: PredefinedTheme[] = [
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    category: 'popular',
    colors: {
      primary: '#3b82f6',
      secondary: '#f3f4f6',
      accent: '#e0f2fe',
      background: '#ffffff',
      foreground: '#333333'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#333333',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#f3f4f6',
      'secondary-foreground': '#0f172a',
      muted: '#f9fafb',
      'muted-foreground': '#64748b',
      accent: '#e0f2fe',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#3b82f6'
    },
    darkModeConfig: {
      background: '#171717',
      foreground: '#e5e5e5',
      card: '#262626',
      'card-foreground': '#f8fafc',
      popover: '#262626',
      'popover-foreground': '#f8fafc',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#262626',
      'secondary-foreground': '#f8fafc',
      muted: '#262626',
      'muted-foreground': '#94a3b8',
      accent: '#1e3a8a',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#404040',
      input: '#404040',
      ring: '#3b82f6'
    }
  },
  {
    id: 'violet-bloom',
    name: 'Violet Bloom',
    category: 'creative',
    colors: {
      primary: '#7033ff',
      secondary: '#edf0f4',
      accent: '#e2ebff',
      background: '#fdfdfd',
      foreground: '#000000'
    },
    lightModeConfig: {
      background: '#fdfdfd',
      foreground: '#000000',
      card: '#fdfdfd',
      'card-foreground': '#000000',
      popover: '#fcfcfc',
      'popover-foreground': '#000000',
      primary: '#7033ff',
      'primary-foreground': '#ffffff',
      secondary: '#edf0f4',
      'secondary-foreground': '#0f172a',
      muted: '#f5f5f5',
      'muted-foreground': '#64748b',
      accent: '#e2ebff',
      'accent-foreground': '#0f172a',
      destructive: '#e54b4f',
      'destructive-foreground': '#ffffff',
      border: '#e7e7ee',
      input: '#ebebeb',
      ring: '#000000'
    },
    darkModeConfig: {
      background: '#1a1b1e',
      foreground: '#f0f0f0',
      card: '#222327',
      'card-foreground': '#f8fafc',
      popover: '#222327',
      'popover-foreground': '#f8fafc',
      primary: '#8c5cff',
      'primary-foreground': '#ffffff',
      secondary: '#2a2c33',
      'secondary-foreground': '#f8fafc',
      muted: '#2a2c33',
      'muted-foreground': '#94a3b8',
      accent: '#1e293b',
      'accent-foreground': '#f8fafc',
      destructive: '#f87171',
      'destructive-foreground': '#ffffff',
      border: '#33353a',
      input: '#33353a',
      ring: '#8c5cff'
    }
  },
  {
    id: 'starry-night',
    name: 'Starry Night',
    category: 'nature',
    colors: {
      primary: '#3a5ba0',
      secondary: '#f7c873',
      accent: '#6ea3c1',
      background: '#f5f7fa',
      foreground: '#1a2238'
    },
    lightModeConfig: {
      background: '#f5f7fa',
      foreground: '#1a2238',
      card: '#e3eaf2',
      'card-foreground': '#000000',
      popover: '#fffbe6',
      'popover-foreground': '#000000',
      primary: '#3a5ba0',
      'primary-foreground': '#ffffff',
      secondary: '#f7c873',
      'secondary-foreground': '#0f172a',
      muted: '#e5e5df',
      'muted-foreground': '#64748b',
      accent: '#6ea3c1',
      'accent-foreground': '#0f172a',
      destructive: '#2d1e2f',
      'destructive-foreground': '#ffffff',
      border: '#b0b8c1',
      input: '#6ea3c1',
      ring: '#f7c873'
    },
    darkModeConfig: {
      background: '#181a24',
      foreground: '#e6eaf3',
      card: '#23243a',
      'card-foreground': '#f8fafc',
      popover: '#23243a',
      'popover-foreground': '#f8fafc',
      primary: '#3a5ba0',
      'primary-foreground': '#ffffff',
      secondary: '#ffe066',
      'secondary-foreground': '#f8fafc',
      muted: '#23243a',
      'muted-foreground': '#94a3b8',
      accent: '#bccdf0',
      'accent-foreground': '#f8fafc',
      destructive: '#a04a6c',
      'destructive-foreground': '#ffffff',
      border: '#2d2e3e',
      input: '#3a5ba0',
      ring: '#ffe066'
    }
  },
  {
    id: 'sunset-horizon',
    name: 'Sunset Horizon',
    category: 'nature',
    colors: {
      primary: '#ff7e5f',
      secondary: '#ffedea',
      accent: '#feb47b',
      background: '#fff9f5',
      foreground: '#3d3436'
    },
    lightModeConfig: {
      background: '#fff9f5',
      foreground: '#3d3436',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#ff7e5f',
      'primary-foreground': '#ffffff',
      secondary: '#ffedea',
      'secondary-foreground': '#0f172a',
      muted: '#fff0eb',
      'muted-foreground': '#64748b',
      accent: '#feb47b',
      'accent-foreground': '#0f172a',
      destructive: '#e63946',
      'destructive-foreground': '#ffffff',
      border: '#ffe0d6',
      input: '#ffe0d6',
      ring: '#ff7e5f'
    },
    darkModeConfig: {
      background: '#2a2024',
      foreground: '#f2e9e4',
      card: '#392f35',
      'card-foreground': '#f8fafc',
      popover: '#392f35',
      'popover-foreground': '#f8fafc',
      primary: '#ff7e5f',
      'primary-foreground': '#ffffff',
      secondary: '#463a41',
      'secondary-foreground': '#f8fafc',
      muted: '#392f35',
      'muted-foreground': '#94a3b8',
      accent: '#feb47b',
      'accent-foreground': '#f8fafc',
      destructive: '#e63946',
      'destructive-foreground': '#ffffff',
      border: '#463a41',
      input: '#463a41',
      ring: '#ff7e5f'
    }
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    category: 'nature',
    colors: {
      primary: '#22c55e',
      secondary: '#e0f2fe',
      accent: '#d1fae5',
      background: '#f0f8ff',
      foreground: '#374151'
    },
    lightModeConfig: {
      background: '#f0f8ff',
      foreground: '#374151',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#22c55e',
      'primary-foreground': '#ffffff',
      secondary: '#e0f2fe',
      'secondary-foreground': '#0f172a',
      muted: '#f3f4f6',
      'muted-foreground': '#64748b',
      accent: '#d1fae5',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#22c55e'
    },
    darkModeConfig: {
      background: '#0f172a',
      foreground: '#d1d5db',
      card: '#1e293b',
      'card-foreground': '#f8fafc',
      popover: '#1e293b',
      'popover-foreground': '#f8fafc',
      primary: '#34d399',
      'primary-foreground': '#ffffff',
      secondary: '#2d3748',
      'secondary-foreground': '#f8fafc',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#374151',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#4b5563',
      input: '#4b5563',
      ring: '#34d399'
    }
  },
  {
    id: 'twitter',
    name: 'Twitter',
    category: 'popular',
    colors: {
      primary: '#1e9df1',
      secondary: '#0f1419',
      accent: '#E3ECF6',
      background: '#ffffff',
      foreground: '#0f1419'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#0f1419',
      card: '#f7f8f8',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#1e9df1',
      'primary-foreground': '#ffffff',
      secondary: '#0f1419',
      'secondary-foreground': '#0f172a',
      muted: '#E5E5E6',
      'muted-foreground': '#64748b',
      accent: '#E3ECF6',
      'accent-foreground': '#0f172a',
      destructive: '#f4212e',
      'destructive-foreground': '#ffffff',
      border: '#e1eaef',
      input: '#f7f9fa',
      ring: '#1da1f2'
    },
    darkModeConfig: {
      background: '#000000',
      foreground: '#e7e9ea',
      card: '#17181c',
      'card-foreground': '#f8fafc',
      popover: '#000000',
      'popover-foreground': '#f8fafc',
      primary: '#1c9cf0',
      'primary-foreground': '#ffffff',
      secondary: '#f0f3f4',
      'secondary-foreground': '#f8fafc',
      muted: '#181818',
      'muted-foreground': '#94a3b8',
      accent: '#061622',
      'accent-foreground': '#f8fafc',
      destructive: '#f4212e',
      'destructive-foreground': '#ffffff',
      border: '#242628',
      input: '#22303c',
      ring: '#1da1f2'
    }
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'popular',
    colors: {
      primary: '#3b82f6',
      secondary: '#f1f5f9',
      accent: '#f1f5f9',
      background: '#ffffff',
      foreground: '#000000'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#000000',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#f1f5f9',
      'secondary-foreground': '#0f172a',
      muted: '#f1f5f9',
      'muted-foreground': '#64748b',
      accent: '#f1f5f9',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#3b82f6'
    },
    darkModeConfig: {
      background: '#0f172a',
      foreground: '#f8fafc',
      card: '#1e293b',
      'card-foreground': '#f8fafc',
      popover: '#1e293b',
      'popover-foreground': '#f8fafc',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#1e293b',
      'secondary-foreground': '#f8fafc',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#1e293b',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#334155',
      input: '#334155',
      ring: '#3b82f6'
    }
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'popular',
    colors: {
      primary: '#c96442',
      secondary: '#e9e6dc',
      accent: '#e9e6dc',
      background: '#faf9f5',
      foreground: '#3d3929'
    },
    lightModeConfig: {
      background: '#faf9f5',
      foreground: '#3d3929',
      card: '#faf9f5',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#c96442',
      'primary-foreground': '#ffffff',
      secondary: '#e9e6dc',
      'secondary-foreground': '#0f172a',
      muted: '#ede9de',
      'muted-foreground': '#64748b',
      accent: '#e9e6dc',
      'accent-foreground': '#0f172a',
      destructive: '#141413',
      'destructive-foreground': '#ffffff',
      border: '#dad9d4',
      input: '#b4b2a7',
      ring: '#c96442'
    },
    darkModeConfig: {
      background: '#262624',
      foreground: '#c3c0b6',
      card: '#262624',
      'card-foreground': '#f8fafc',
      popover: '#30302e',
      'popover-foreground': '#f8fafc',
      primary: '#d97757',
      'primary-foreground': '#ffffff',
      secondary: '#faf9f5',
      'secondary-foreground': '#f8fafc',
      muted: '#1b1b19',
      'muted-foreground': '#94a3b8',
      accent: '#1a1915',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#3e3e38',
      input: '#52514a',
      ring: '#d97757'
    }
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'popular',
    colors: {
      primary: '#72e3ad',
      secondary: '#fdfdfd',
      accent: '#ededed',
      background: '#fcfcfc',
      foreground: '#171717'
    },
    lightModeConfig: {
      background: '#fcfcfc',
      foreground: '#171717',
      card: '#fcfcfc',
      'card-foreground': '#000000',
      popover: '#fcfcfc',
      'popover-foreground': '#000000',
      primary: '#72e3ad',
      'primary-foreground': '#ffffff',
      secondary: '#fdfdfd',
      'secondary-foreground': '#0f172a',
      muted: '#ededed',
      'muted-foreground': '#64748b',
      accent: '#ededed',
      'accent-foreground': '#0f172a',
      destructive: '#ca3214',
      'destructive-foreground': '#ffffff',
      border: '#dfdfdf',
      input: '#f6f6f6',
      ring: '#72e3ad'
    },
    darkModeConfig: {
      background: '#121212',
      foreground: '#e2e8f0',
      card: '#171717',
      'card-foreground': '#f8fafc',
      popover: '#242424',
      'popover-foreground': '#f8fafc',
      primary: '#006239',
      'primary-foreground': '#ffffff',
      secondary: '#242424',
      'secondary-foreground': '#f8fafc',
      muted: '#1f1f1f',
      'muted-foreground': '#94a3b8',
      accent: '#313131',
      'accent-foreground': '#f8fafc',
      destructive: '#541c15',
      'destructive-foreground': '#ffffff',
      border: '#292929',
      input: '#242424',
      ring: '#4ade80'
    }
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'creative',
    colors: {
      primary: '#ff00c8',
      secondary: '#f0f0ff',
      accent: '#00ffcc',
      background: '#f8f9fa',
      foreground: '#0c0c1d'
    },
    lightModeConfig: {
      background: '#f8f9fa',
      foreground: '#0c0c1d',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#ff00c8',
      'primary-foreground': '#ffffff',
      secondary: '#f0f0ff',
      'secondary-foreground': '#0f172a',
      muted: '#f0f0ff',
      'muted-foreground': '#64748b',
      accent: '#00ffcc',
      'accent-foreground': '#0f172a',
      destructive: '#ff3d00',
      'destructive-foreground': '#ffffff',
      border: '#dfe6e9',
      input: '#dfe6e9',
      ring: '#ff00c8'
    },
    darkModeConfig: {
      background: '#0c0c1d',
      foreground: '#eceff4',
      card: '#1e1e3f',
      'card-foreground': '#f8fafc',
      popover: '#1e1e3f',
      'popover-foreground': '#f8fafc',
      primary: '#ff00c8',
      'primary-foreground': '#ffffff',
      secondary: '#1e1e3f',
      'secondary-foreground': '#f8fafc',
      muted: '#1e1e3f',
      'muted-foreground': '#94a3b8',
      accent: '#00ffcc',
      'accent-foreground': '#f8fafc',
      destructive: '#ff3d00',
      'destructive-foreground': '#ffffff',
      border: '#2e2e5e',
      input: '#2e2e5e',
      ring: '#ff00c8'
    }
  },
  {
    id: 'neo-brutalism',
    name: 'Neo Brutalism',
    category: 'creative',
    colors: {
      primary: '#ff3333',
      secondary: '#ffff00',
      accent: '#0066ff',
      background: '#ffffff',
      foreground: '#000000'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#000000',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#ff3333',
      'primary-foreground': '#ffffff',
      secondary: '#ffff00',
      'secondary-foreground': '#0f172a',
      muted: '#f0f0f0',
      'muted-foreground': '#64748b',
      accent: '#0066ff',
      'accent-foreground': '#0f172a',
      destructive: '#000000',
      'destructive-foreground': '#ffffff',
      border: '#000000',
      input: '#000000',
      ring: '#ff3333'
    },
    darkModeConfig: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#333333',
      'card-foreground': '#f8fafc',
      popover: '#333333',
      'popover-foreground': '#f8fafc',
      primary: '#ff6666',
      'primary-foreground': '#ffffff',
      secondary: '#ffff33',
      'secondary-foreground': '#f8fafc',
      muted: '#333333',
      'muted-foreground': '#94a3b8',
      accent: '#3399ff',
      'accent-foreground': '#f8fafc',
      destructive: '#ffffff',
      'destructive-foreground': '#ffffff',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#ff6666'
    }
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    category: 'specialty',
    colors: {
      primary: '#8839ef',
      secondary: '#ccd0da',
      accent: '#04a5e5',
      background: '#eff1f5',
      foreground: '#4c4f69'
    },
    lightModeConfig: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ccd0da',
      'popover-foreground': '#000000',
      primary: '#8839ef',
      'primary-foreground': '#ffffff',
      secondary: '#ccd0da',
      'secondary-foreground': '#0f172a',
      muted: '#dce0e8',
      'muted-foreground': '#64748b',
      accent: '#04a5e5',
      'accent-foreground': '#0f172a',
      destructive: '#d20f39',
      'destructive-foreground': '#ffffff',
      border: '#bcc0cc',
      input: '#ccd0da',
      ring: '#8839ef'
    },
    darkModeConfig: {
      background: '#181825',
      foreground: '#cdd6f4',
      card: '#1e1e2e',
      'card-foreground': '#f8fafc',
      popover: '#45475a',
      'popover-foreground': '#f8fafc',
      primary: '#cba6f7',
      'primary-foreground': '#ffffff',
      secondary: '#585b70',
      'secondary-foreground': '#f8fafc',
      muted: '#292c3c',
      'muted-foreground': '#94a3b8',
      accent: '#89dceb',
      'accent-foreground': '#f8fafc',
      destructive: '#f38ba8',
      'destructive-foreground': '#ffffff',
      border: '#313244',
      input: '#313244',
      ring: '#cba6f7'
    }
  },
  {
    id: 'retro-arcade',
    name: 'Retro Arcade',
    category: 'creative',
    colors: {
      primary: '#d33682',
      secondary: '#2aa198',
      accent: '#cb4b16',
      background: '#fdf6e3',
      foreground: '#073642'
    },
    lightModeConfig: {
      background: '#fdf6e3',
      foreground: '#073642',
      card: '#eee8d5',
      'card-foreground': '#000000',
      popover: '#eee8d5',
      'popover-foreground': '#000000',
      primary: '#d33682',
      'primary-foreground': '#ffffff',
      secondary: '#2aa198',
      'secondary-foreground': '#0f172a',
      muted: '#93a1a1',
      'muted-foreground': '#64748b',
      accent: '#cb4b16',
      'accent-foreground': '#0f172a',
      destructive: '#dc322f',
      'destructive-foreground': '#ffffff',
      border: '#839496',
      input: '#839496',
      ring: '#d33682'
    },
    darkModeConfig: {
      background: '#002b36',
      foreground: '#93a1a1',
      card: '#073642',
      'card-foreground': '#f8fafc',
      popover: '#073642',
      'popover-foreground': '#f8fafc',
      primary: '#d33682',
      'primary-foreground': '#ffffff',
      secondary: '#2aa198',
      'secondary-foreground': '#f8fafc',
      muted: '#586e75',
      'muted-foreground': '#94a3b8',
      accent: '#cb4b16',
      'accent-foreground': '#f8fafc',
      destructive: '#dc322f',
      'destructive-foreground': '#ffffff',
      border: '#586e75',
      input: '#586e75',
      ring: '#d33682'
    }
  },
  {
    id: 'mono',
    name: 'Mono',
    category: 'monochrome',
    colors: {
      primary: '#737373',
      secondary: '#f5f5f5',
      accent: '#f5f5f5',
      background: '#ffffff',
      foreground: '#0a0a0a'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#737373',
      'primary-foreground': '#ffffff',
      secondary: '#f5f5f5',
      'secondary-foreground': '#0f172a',
      muted: '#f5f5f5',
      'muted-foreground': '#64748b',
      accent: '#f5f5f5',
      'accent-foreground': '#0f172a',
      destructive: '#e7000b',
      'destructive-foreground': '#ffffff',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#a1a1a1'
    },
    darkModeConfig: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#191919',
      'card-foreground': '#f8fafc',
      popover: '#262626',
      'popover-foreground': '#f8fafc',
      primary: '#737373',
      'primary-foreground': '#ffffff',
      secondary: '#262626',
      'secondary-foreground': '#f8fafc',
      muted: '#262626',
      'muted-foreground': '#94a3b8',
      accent: '#404040',
      'accent-foreground': '#f8fafc',
      destructive: '#ff6467',
      'destructive-foreground': '#ffffff',
      border: '#383838',
      input: '#525252',
      ring: '#737373'
    }
  },
  {
    id: 'vintage-paper',
    name: 'Vintage Paper',
    category: 'monochrome',
    colors: {
      primary: '#a67c52',
      secondary: '#e2d8c3',
      accent: '#d4c8aa',
      background: '#f5f1e6',
      foreground: '#4a3f35'
    },
    lightModeConfig: {
      background: '#f5f1e6',
      foreground: '#4a3f35',
      card: '#fffcf5',
      'card-foreground': '#000000',
      popover: '#fffcf5',
      'popover-foreground': '#000000',
      primary: '#a67c52',
      'primary-foreground': '#ffffff',
      secondary: '#e2d8c3',
      'secondary-foreground': '#0f172a',
      muted: '#ece5d8',
      'muted-foreground': '#64748b',
      accent: '#d4c8aa',
      'accent-foreground': '#0f172a',
      destructive: '#b54a35',
      'destructive-foreground': '#ffffff',
      border: '#dbd0ba',
      input: '#dbd0ba',
      ring: '#a67c52'
    },
    darkModeConfig: {
      background: '#2d2621',
      foreground: '#ece5d8',
      card: '#3a322c',
      'card-foreground': '#f8fafc',
      popover: '#3a322c',
      'popover-foreground': '#f8fafc',
      primary: '#c0a080',
      'primary-foreground': '#ffffff',
      secondary: '#4a4039',
      'secondary-foreground': '#f8fafc',
      muted: '#3a322c',
      'muted-foreground': '#94a3b8',
      accent: '#59493e',
      'accent-foreground': '#f8fafc',
      destructive: '#b54a35',
      'destructive-foreground': '#ffffff',
      border: '#4a4039',
      input: '#4a4039',
      ring: '#c0a080'
    }
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    category: 'nature',
    colors: {
      primary: '#16a34a',
      secondary: '#dcfce7',
      accent: '#bbf7d0',
      background: '#f0fdf4',
      foreground: '#052e16'
    },
    lightModeConfig: {
      background: '#f0fdf4',
      foreground: '#052e16',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#16a34a',
      'primary-foreground': '#ffffff',
      secondary: '#dcfce7',
      'secondary-foreground': '#0f172a',
      muted: '#f3f4f6',
      'muted-foreground': '#64748b',
      accent: '#bbf7d0',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#16a34a'
    },
    darkModeConfig: {
      background: '#0f1e0f',
      foreground: '#dcfce7',
      card: '#1a2e1a',
      'card-foreground': '#f8fafc',
      popover: '#1a2e1a',
      'popover-foreground': '#f8fafc',
      primary: '#22c55e',
      'primary-foreground': '#ffffff',
      secondary: '#2d4a2d',
      'secondary-foreground': '#f8fafc',
      muted: '#1a2e1a',
      'muted-foreground': '#94a3b8',
      accent: '#374151',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#374151',
      input: '#374151',
      ring: '#22c55e'
    }
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    category: 'nature',
    colors: {
      primary: '#fb7185',
      secondary: '#fce7f3',
      accent: '#fbbf24',
      background: '#fffbeb',
      foreground: '#451a03'
    },
    lightModeConfig: {
      background: '#fffbeb',
      foreground: '#451a03',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#fb7185',
      'primary-foreground': '#ffffff',
      secondary: '#fce7f3',
      'secondary-foreground': '#0f172a',
      muted: '#fef3c7',
      'muted-foreground': '#64748b',
      accent: '#fbbf24',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#fed7aa',
      input: '#fed7aa',
      ring: '#fb7185'
    },
    darkModeConfig: {
      background: '#2d1b1b',
      foreground: '#fce7f3',
      card: '#3d2626',
      'card-foreground': '#f8fafc',
      popover: '#3d2626',
      'popover-foreground': '#f8fafc',
      primary: '#fb7185',
      'primary-foreground': '#ffffff',
      secondary: '#4a3030',
      'secondary-foreground': '#f8fafc',
      muted: '#3d2626',
      'muted-foreground': '#94a3b8',
      accent: '#fbbf24',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#4a3030',
      input: '#4a3030',
      ring: '#fb7185'
    }
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'nature',
    colors: {
      primary: '#1e40af',
      secondary: '#dbeafe',
      accent: '#bfdbfe',
      background: '#f8fafc',
      foreground: '#1e293b'
    },
    lightModeConfig: {
      background: '#f8fafc',
      foreground: '#1e293b',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#1e40af',
      'primary-foreground': '#ffffff',
      secondary: '#dbeafe',
      'secondary-foreground': '#0f172a',
      muted: '#f1f5f9',
      'muted-foreground': '#64748b',
      accent: '#bfdbfe',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#1e40af'
    },
    darkModeConfig: {
      background: '#0c1220',
      foreground: '#dbeafe',
      card: '#1e293b',
      'card-foreground': '#f8fafc',
      popover: '#1e293b',
      'popover-foreground': '#f8fafc',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#334155',
      'secondary-foreground': '#f8fafc',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#475569',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#475569',
      input: '#475569',
      ring: '#3b82f6'
    }
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    category: 'corporate',
    colors: {
      primary: '#2563eb',
      secondary: '#f1f5f9',
      accent: '#e2e8f0',
      background: '#ffffff',
      foreground: '#1e293b'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#1e293b',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#2563eb',
      'primary-foreground': '#ffffff',
      secondary: '#f1f5f9',
      'secondary-foreground': '#0f172a',
      muted: '#f8fafc',
      'muted-foreground': '#64748b',
      accent: '#e2e8f0',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#2563eb'
    },
    darkModeConfig: {
      background: '#0f172a',
      foreground: '#f1f5f9',
      card: '#1e293b',
      'card-foreground': '#f8fafc',
      popover: '#1e293b',
      'popover-foreground': '#f8fafc',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#334155',
      'secondary-foreground': '#f8fafc',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#475569',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#475569',
      input: '#475569',
      ring: '#3b82f6'
    }
  },
  {
    id: 'enterprise-gray',
    name: 'Enterprise Gray',
    category: 'corporate',
    colors: {
      primary: '#374151',
      secondary: '#f9fafb',
      accent: '#e5e7eb',
      background: '#ffffff',
      foreground: '#111827'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#111827',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#374151',
      'primary-foreground': '#ffffff',
      secondary: '#f9fafb',
      'secondary-foreground': '#0f172a',
      muted: '#f3f4f6',
      'muted-foreground': '#64748b',
      accent: '#e5e7eb',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#d1d5db',
      input: '#d1d5db',
      ring: '#374151'
    },
    darkModeConfig: {
      background: '#111827',
      foreground: '#f9fafb',
      card: '#1f2937',
      'card-foreground': '#f8fafc',
      popover: '#1f2937',
      'popover-foreground': '#f8fafc',
      primary: '#6b7280',
      'primary-foreground': '#ffffff',
      secondary: '#374151',
      'secondary-foreground': '#f8fafc',
      muted: '#1f2937',
      'muted-foreground': '#94a3b8',
      accent: '#4b5563',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#4b5563',
      input: '#4b5563',
      ring: '#6b7280'
    }
  },
  {
    id: 'professional-green',
    name: 'Professional Green',
    category: 'corporate',
    colors: {
      primary: '#059669',
      secondary: '#ecfdf5',
      accent: '#d1fae5',
      background: '#ffffff',
      foreground: '#064e3b'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#064e3b',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#059669',
      'primary-foreground': '#ffffff',
      secondary: '#ecfdf5',
      'secondary-foreground': '#0f172a',
      muted: '#f0fdf4',
      'muted-foreground': '#64748b',
      accent: '#d1fae5',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#bbf7d0',
      input: '#bbf7d0',
      ring: '#059669'
    },
    darkModeConfig: {
      background: '#064e3b',
      foreground: '#ecfdf5',
      card: '#0f5d4f',
      'card-foreground': '#f8fafc',
      popover: '#0f5d4f',
      'popover-foreground': '#f8fafc',
      primary: '#10b981',
      'primary-foreground': '#ffffff',
      secondary: '#1a6b5a',
      'secondary-foreground': '#f8fafc',
      muted: '#0f5d4f',
      'muted-foreground': '#94a3b8',
      accent: '#22c55e',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#1a6b5a',
      input: '#1a6b5a',
      ring: '#10b981'
    }
  },
  {
    id: 'rainbow-gradient',
    name: 'Rainbow Gradient',
    category: 'creative',
    colors: {
      primary: '#ec4899',
      secondary: '#f3e8ff',
      accent: '#a78bfa',
      background: '#fefcff',
      foreground: '#3b0764'
    },
    lightModeConfig: {
      background: '#fefcff',
      foreground: '#3b0764',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#ec4899',
      'primary-foreground': '#ffffff',
      secondary: '#f3e8ff',
      'secondary-foreground': '#0f172a',
      muted: '#faf5ff',
      'muted-foreground': '#64748b',
      accent: '#a78bfa',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e9d5ff',
      input: '#e9d5ff',
      ring: '#ec4899'
    },
    darkModeConfig: {
      background: '#3b0764',
      foreground: '#f3e8ff',
      card: '#4c1d95',
      'card-foreground': '#f8fafc',
      popover: '#4c1d95',
      'popover-foreground': '#f8fafc',
      primary: '#f472b6',
      'primary-foreground': '#ffffff',
      secondary: '#5b21b6',
      'secondary-foreground': '#f8fafc',
      muted: '#4c1d95',
      'muted-foreground': '#94a3b8',
      accent: '#a78bfa',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#5b21b6',
      input: '#5b21b6',
      ring: '#f472b6'
    }
  },
  {
    id: 'neon-glow',
    name: 'Neon Glow',
    category: 'creative',
    colors: {
      primary: '#10b981',
      secondary: '#1f2937',
      accent: '#6366f1',
      background: '#0f1419',
      foreground: '#ecfdf5'
    },
    lightModeConfig: {
      background: '#f0fdf4',
      foreground: '#0f1419',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#10b981',
      'primary-foreground': '#ffffff',
      secondary: '#f3f4f6',
      'secondary-foreground': '#0f172a',
      muted: '#ecfdf5',
      'muted-foreground': '#64748b',
      accent: '#6366f1',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#d1fae5',
      input: '#d1fae5',
      ring: '#10b981'
    },
    darkModeConfig: {
      background: '#0f1419',
      foreground: '#ecfdf5',
      card: '#1f2937',
      'card-foreground': '#f8fafc',
      popover: '#1f2937',
      'popover-foreground': '#f8fafc',
      primary: '#10b981',
      'primary-foreground': '#ffffff',
      secondary: '#374151',
      'secondary-foreground': '#f8fafc',
      muted: '#1f2937',
      'muted-foreground': '#94a3b8',
      accent: '#6366f1',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#374151',
      input: '#374151',
      ring: '#10b981'
    }
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    category: 'creative',
    colors: {
      primary: '#0ea5e9',
      secondary: '#e0f2fe',
      accent: '#7dd3fc',
      background: '#f0f9ff',
      foreground: '#0c4a6e'
    },
    lightModeConfig: {
      background: '#f0f9ff',
      foreground: '#0c4a6e',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#0ea5e9',
      'primary-foreground': '#ffffff',
      secondary: '#e0f2fe',
      'secondary-foreground': '#0f172a',
      muted: '#f0f9ff',
      'muted-foreground': '#64748b',
      accent: '#7dd3fc',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#bae6fd',
      input: '#bae6fd',
      ring: '#0ea5e9'
    },
    darkModeConfig: {
      background: '#0c1220',
      foreground: '#e0f2fe',
      card: '#1e293b',
      'card-foreground': '#f8fafc',
      popover: '#1e293b',
      'popover-foreground': '#f8fafc',
      primary: '#0ea5e9',
      'primary-foreground': '#ffffff',
      secondary: '#334155',
      'secondary-foreground': '#f8fafc',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#7dd3fc',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#334155',
      input: '#334155',
      ring: '#0ea5e9'
    }
  },
  {
    id: 'black-white',
    name: 'Black & White',
    category: 'monochrome',
    colors: {
      primary: '#000000',
      secondary: '#f5f5f5',
      accent: '#d4d4d4',
      background: '#ffffff',
      foreground: '#000000'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#000000',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#000000',
      'primary-foreground': '#ffffff',
      secondary: '#f5f5f5',
      'secondary-foreground': '#0f172a',
      muted: '#f9f9f9',
      'muted-foreground': '#64748b',
      accent: '#d4d4d4',
      'accent-foreground': '#0f172a',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#000000'
    },
    darkModeConfig: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#1a1a1a',
      'card-foreground': '#f8fafc',
      popover: '#1a1a1a',
      'popover-foreground': '#f8fafc',
      primary: '#ffffff',
      'primary-foreground': '#000000',
      secondary: '#262626',
      'secondary-foreground': '#f8fafc',
      muted: '#1a1a1a',
      'muted-foreground': '#94a3b8',
      accent: '#404040',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#404040',
      input: '#404040',
      ring: '#ffffff'
    }
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    category: 'monochrome',
    colors: {
      primary: '#525252',
      secondary: '#f3f4f6',
      accent: '#e5e7eb',
      background: '#fafafa',
      foreground: '#171717'
    },
    lightModeConfig: {
      background: '#fafafa',
      foreground: '#171717',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#525252',
      'primary-foreground': '#ffffff',
      secondary: '#f3f4f6',
      'secondary-foreground': '#0f172a',
      muted: '#f9fafb',
      'muted-foreground': '#64748b',
      accent: '#e5e7eb',
      'accent-foreground': '#0f172a',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#d1d5db',
      input: '#d1d5db',
      ring: '#525252'
    },
    darkModeConfig: {
      background: '#171717',
      foreground: '#f3f4f6',
      card: '#262626',
      'card-foreground': '#f8fafc',
      popover: '#262626',
      'popover-foreground': '#f8fafc',
      primary: '#737373',
      'primary-foreground': '#ffffff',
      secondary: '#404040',
      'secondary-foreground': '#f8fafc',
      muted: '#262626',
      'muted-foreground': '#94a3b8',
      accent: '#525252',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#525252',
      input: '#525252',
      ring: '#737373'
    }
  },
  {
    id: 'dracula',
    name: 'Dracula',
    category: 'specialty',
    colors: {
      primary: '#bd93f9',
      secondary: '#44475a',
      accent: '#ff79c6',
      background: '#282a36',
      foreground: '#f8f8f2'
    },
    lightModeConfig: {
      background: '#f8f8f2',
      foreground: '#282a36',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#6272a4',
      'primary-foreground': '#ffffff',
      secondary: '#f1f1f1',
      'secondary-foreground': '#0f172a',
      muted: '#f4f4f4',
      'muted-foreground': '#64748b',
      accent: '#bd93f9',
      'accent-foreground': '#0f172a',
      destructive: '#ff5555',
      'destructive-foreground': '#ffffff',
      border: '#e0e0e0',
      input: '#e0e0e0',
      ring: '#6272a4'
    },
    darkModeConfig: {
      background: '#282a36',
      foreground: '#f8f8f2',
      card: '#44475a',
      'card-foreground': '#f8fafc',
      popover: '#44475a',
      'popover-foreground': '#f8fafc',
      primary: '#bd93f9',
      'primary-foreground': '#ffffff',
      secondary: '#6272a4',
      'secondary-foreground': '#f8fafc',
      muted: '#44475a',
      'muted-foreground': '#94a3b8',
      accent: '#ff79c6',
      'accent-foreground': '#f8fafc',
      destructive: '#ff5555',
      'destructive-foreground': '#ffffff',
      border: '#6272a4',
      input: '#6272a4',
      ring: '#bd93f9'
    }
  },
  {
    id: 'nord',
    name: 'Nord',
    category: 'specialty',
    colors: {
      primary: '#5e81ac',
      secondary: '#eceff4',
      accent: '#88c0d0',
      background: '#ffffff',
      foreground: '#2e3440'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#2e3440',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#5e81ac',
      'primary-foreground': '#ffffff',
      secondary: '#eceff4',
      'secondary-foreground': '#0f172a',
      muted: '#f8f9fa',
      'muted-foreground': '#64748b',
      accent: '#88c0d0',
      'accent-foreground': '#0f172a',
      destructive: '#bf616a',
      'destructive-foreground': '#ffffff',
      border: '#d8dee9',
      input: '#d8dee9',
      ring: '#5e81ac'
    },
    darkModeConfig: {
      background: '#2e3440',
      foreground: '#eceff4',
      card: '#3b4252',
      'card-foreground': '#f8fafc',
      popover: '#3b4252',
      'popover-foreground': '#f8fafc',
      primary: '#81a1c1',
      'primary-foreground': '#ffffff',
      secondary: '#434c5e',
      'secondary-foreground': '#f8fafc',
      muted: '#3b4252',
      'muted-foreground': '#94a3b8',
      accent: '#88c0d0',
      'accent-foreground': '#f8fafc',
      destructive: '#bf616a',
      'destructive-foreground': '#ffffff',
      border: '#434c5e',
      input: '#434c5e',
      ring: '#81a1c1'
    }
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    category: 'specialty',
    colors: {
      primary: '#fe8019',
      secondary: '#fbf1c7',
      accent: '#fabd2f',
      background: '#fbf1c7',
      foreground: '#3c3836'
    },
    lightModeConfig: {
      background: '#fbf1c7',
      foreground: '#3c3836',
      card: '#f9f5d7',
      'card-foreground': '#000000',
      popover: '#f9f5d7',
      'popover-foreground': '#000000',
      primary: '#fe8019',
      'primary-foreground': '#ffffff',
      secondary: '#ebdbb2',
      'secondary-foreground': '#0f172a',
      muted: '#f2e5bc',
      'muted-foreground': '#64748b',
      accent: '#fabd2f',
      'accent-foreground': '#0f172a',
      destructive: '#cc241d',
      'destructive-foreground': '#ffffff',
      border: '#d5c4a1',
      input: '#d5c4a1',
      ring: '#fe8019'
    },
    darkModeConfig: {
      background: '#282828',
      foreground: '#fbf1c7',
      card: '#3c3836',
      'card-foreground': '#f8fafc',
      popover: '#3c3836',
      'popover-foreground': '#f8fafc',
      primary: '#fe8019',
      'primary-foreground': '#ffffff',
      secondary: '#504945',
      'secondary-foreground': '#f8fafc',
      muted: '#3c3836',
      'muted-foreground': '#94a3b8',
      accent: '#fabd2f',
      'accent-foreground': '#f8fafc',
      destructive: '#fb4934',
      'destructive-foreground': '#ffffff',
      border: '#504945',
      input: '#504945',
      ring: '#fe8019'
    }
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    category: 'specialty',
    colors: {
      primary: '#7aa2f7',
      secondary: '#1a1b26',
      accent: '#bb9af7',
      background: '#1a1b26',
      foreground: '#c0caf5'
    },
    lightModeConfig: {
      background: '#d5d6db',
      foreground: '#1a1b26',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#3d59a1',
      'primary-foreground': '#ffffff',
      secondary: '#e9e9ed',
      'secondary-foreground': '#0f172a',
      muted: '#f0f0f4',
      'muted-foreground': '#64748b',
      accent: '#8f5cf4',
      'accent-foreground': '#0f172a',
      destructive: '#f7768e',
      'destructive-foreground': '#ffffff',
      border: '#cbccd1',
      input: '#cbccd1',
      ring: '#3d59a1'
    },
    darkModeConfig: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      card: '#24283b',
      'card-foreground': '#f8fafc',
      popover: '#24283b',
      'popover-foreground': '#f8fafc',
      primary: '#7aa2f7',
      'primary-foreground': '#ffffff',
      secondary: '#414868',
      'secondary-foreground': '#f8fafc',
      muted: '#24283b',
      'muted-foreground': '#94a3b8',
      accent: '#bb9af7',
      'accent-foreground': '#f8fafc',
      destructive: '#f7768e',
      'destructive-foreground': '#ffffff',
      border: '#414868',
      input: '#414868',
      ring: '#7aa2f7'
    }
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    category: 'specialty',
    colors: {
      primary: '#268bd2',
      secondary: '#fdf6e3',
      accent: '#2aa198',
      background: '#fdf6e3',
      foreground: '#657b83'
    },
    lightModeConfig: {
      background: '#fdf6e3',
      foreground: '#657b83',
      card: '#eee8d5',
      'card-foreground': '#000000',
      popover: '#eee8d5',
      'popover-foreground': '#000000',
      primary: '#268bd2',
      'primary-foreground': '#ffffff',
      secondary: '#eee8d5',
      'secondary-foreground': '#0f172a',
      muted: '#93a1a1',
      'muted-foreground': '#64748b',
      accent: '#2aa198',
      'accent-foreground': '#0f172a',
      destructive: '#dc322f',
      'destructive-foreground': '#ffffff',
      border: '#839496',
      input: '#839496',
      ring: '#268bd2'
    },
    darkModeConfig: {
      background: '#002b36',
      foreground: '#839496',
      card: '#073642',
      'card-foreground': '#f8fafc',
      popover: '#073642',
      'popover-foreground': '#f8fafc',
      primary: '#268bd2',
      'primary-foreground': '#ffffff',
      secondary: '#586e75',
      'secondary-foreground': '#f8fafc',
      muted: '#073642',
      'muted-foreground': '#94a3b8',
      accent: '#2aa198',
      'accent-foreground': '#f8fafc',
      destructive: '#dc322f',
      'destructive-foreground': '#ffffff',
      border: '#586e75',
      input: '#586e75',
      ring: '#268bd2'
    }
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    category: 'popular',
    colors: {
      primary: '#0969da',
      secondary: '#f6f8fa',
      accent: '#dbeafe',
      background: '#ffffff',
      foreground: '#24292f'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#24292f',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#0969da',
      'primary-foreground': '#ffffff',
      secondary: '#f6f8fa',
      'secondary-foreground': '#0f172a',
      muted: '#f6f8fa',
      'muted-foreground': '#64748b',
      accent: '#dbeafe',
      'accent-foreground': '#0f172a',
      destructive: '#cf222e',
      'destructive-foreground': '#ffffff',
      border: '#d0d7de',
      input: '#d0d7de',
      ring: '#0969da'
    },
    darkModeConfig: {
      background: '#0d1117',
      foreground: '#e6edf3',
      card: '#161b22',
      'card-foreground': '#f8fafc',
      popover: '#161b22',
      'popover-foreground': '#f8fafc',
      primary: '#2f81f7',
      'primary-foreground': '#ffffff',
      secondary: '#21262d',
      'secondary-foreground': '#f8fafc',
      muted: '#161b22',
      'muted-foreground': '#94a3b8',
      accent: '#1e3a8a',
      'accent-foreground': '#f8fafc',
      destructive: '#da3633',
      'destructive-foreground': '#ffffff',
      border: '#30363d',
      input: '#30363d',
      ring: '#2f81f7'
    }
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'popular',
    colors: {
      primary: '#5e6ad2',
      secondary: '#f6f6f7',
      accent: '#e4e4e7',
      background: '#fafafa',
      foreground: '#0d0e10'
    },
    lightModeConfig: {
      background: '#fafafa',
      foreground: '#0d0e10',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#5e6ad2',
      'primary-foreground': '#ffffff',
      secondary: '#f6f6f7',
      'secondary-foreground': '#0f172a',
      muted: '#f1f1f3',
      'muted-foreground': '#64748b',
      accent: '#e4e4e7',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e4e4e7',
      input: '#e4e4e7',
      ring: '#5e6ad2'
    },
    darkModeConfig: {
      background: '#0d0e10',
      foreground: '#f6f6f7',
      card: '#1a1b1e',
      'card-foreground': '#f8fafc',
      popover: '#1a1b1e',
      'popover-foreground': '#f8fafc',
      primary: '#8b93ff',
      'primary-foreground': '#ffffff',
      secondary: '#27282c',
      'secondary-foreground': '#f8fafc',
      muted: '#1a1b1e',
      'muted-foreground': '#94a3b8',
      accent: '#333438',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#333438',
      input: '#333438',
      ring: '#8b93ff'
    }
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'popular',
    colors: {
      primary: '#2eaadc',
      secondary: '#f7f6f3',
      accent: '#e9e5e0',
      background: '#ffffff',
      foreground: '#37352f'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#37352f',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#2eaadc',
      'primary-foreground': '#ffffff',
      secondary: '#f7f6f3',
      'secondary-foreground': '#0f172a',
      muted: '#f1f1ef',
      'muted-foreground': '#64748b',
      accent: '#e9e5e0',
      'accent-foreground': '#0f172a',
      destructive: '#eb5147',
      'destructive-foreground': '#ffffff',
      border: '#e9e5e0',
      input: '#e9e5e0',
      ring: '#2eaadc'
    },
    darkModeConfig: {
      background: '#191919',
      foreground: '#f7f6f3',
      card: '#2f2f2f',
      'card-foreground': '#f8fafc',
      popover: '#2f2f2f',
      'popover-foreground': '#f8fafc',
      primary: '#2eaadc',
      'primary-foreground': '#ffffff',
      secondary: '#3f3f3f',
      'secondary-foreground': '#f8fafc',
      muted: '#2f2f2f',
      'muted-foreground': '#94a3b8',
      accent: '#454545',
      'accent-foreground': '#f8fafc',
      destructive: '#eb5147',
      'destructive-foreground': '#ffffff',
      border: '#454545',
      input: '#454545',
      ring: '#2eaadc'
    }
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'popular',
    colors: {
      primary: '#5865f2',
      secondary: '#f2f3f5',
      accent: '#e3e5e8',
      background: '#ffffff',
      foreground: '#2e3338'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#2e3338',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#5865f2',
      'primary-foreground': '#ffffff',
      secondary: '#f2f3f5',
      'secondary-foreground': '#0f172a',
      muted: '#f9f9f9',
      'muted-foreground': '#64748b',
      accent: '#e3e5e8',
      'accent-foreground': '#0f172a',
      destructive: '#ed4245',
      'destructive-foreground': '#ffffff',
      border: '#e3e5e8',
      input: '#e3e5e8',
      ring: '#5865f2'
    },
    darkModeConfig: {
      background: '#313338',
      foreground: '#f2f3f5',
      card: '#2b2d31',
      'card-foreground': '#f8fafc',
      popover: '#2b2d31',
      'popover-foreground': '#f8fafc',
      primary: '#5865f2',
      'primary-foreground': '#ffffff',
      secondary: '#4e5058',
      'secondary-foreground': '#f8fafc',
      muted: '#2b2d31',
      'muted-foreground': '#94a3b8',
      accent: '#404249',
      'accent-foreground': '#f8fafc',
      destructive: '#ed4245',
      'destructive-foreground': '#ffffff',
      border: '#404249',
      input: '#404249',
      ring: '#5865f2'
    }
  },
  {
    id: 'spotify',
    name: 'Spotify',
    category: 'popular',
    colors: {
      primary: '#1db954',
      secondary: '#f6f6f6',
      accent: '#e8f5e8',
      background: '#ffffff',
      foreground: '#191414'
    },
    lightModeConfig: {
      background: '#ffffff',
      foreground: '#191414',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#1db954',
      'primary-foreground': '#ffffff',
      secondary: '#f6f6f6',
      'secondary-foreground': '#0f172a',
      muted: '#f8f8f8',
      'muted-foreground': '#64748b',
      accent: '#e8f5e8',
      'accent-foreground': '#0f172a',
      destructive: '#e22134',
      'destructive-foreground': '#ffffff',
      border: '#e0e0e0',
      input: '#e0e0e0',
      ring: '#1db954'
    },
    darkModeConfig: {
      background: '#191414',
      foreground: '#ffffff',
      card: '#282828',
      'card-foreground': '#f8fafc',
      popover: '#282828',
      'popover-foreground': '#f8fafc',
      primary: '#1db954',
      'primary-foreground': '#ffffff',
      secondary: '#404040',
      'secondary-foreground': '#f8fafc',
      muted: '#282828',
      'muted-foreground': '#94a3b8',
      accent: '#535353',
      'accent-foreground': '#f8fafc',
      destructive: '#e22134',
      'destructive-foreground': '#ffffff',
      border: '#535353',
      input: '#535353',
      ring: '#1db954'
    }
  },
  {
    id: 'orange-sunset',
    name: 'Orange Sunset',
    category: 'nature',
    colors: {
      primary: '#fb923c',
      secondary: '#fed7aa',
      accent: '#f97316',
      background: '#fff7ed',
      foreground: '#9a3412'
    },
    lightModeConfig: {
      background: '#fff7ed',
      foreground: '#9a3412',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#fb923c',
      'primary-foreground': '#ffffff',
      secondary: '#fed7aa',
      'secondary-foreground': '#0f172a',
      muted: '#ffedd5',
      'muted-foreground': '#64748b',
      accent: '#f97316',
      'accent-foreground': '#0f172a',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#fdba74',
      input: '#fdba74',
      ring: '#fb923c'
    },
    darkModeConfig: {
      background: '#431407',
      foreground: '#fed7aa',
      card: '#7c2d12',
      'card-foreground': '#f8fafc',
      popover: '#7c2d12',
      'popover-foreground': '#f8fafc',
      primary: '#fb923c',
      'primary-foreground': '#ffffff',
      secondary: '#9a3412',
      'secondary-foreground': '#f8fafc',
      muted: '#7c2d12',
      'muted-foreground': '#94a3b8',
      accent: '#f97316',
      'accent-foreground': '#f8fafc',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#9a3412',
      input: '#9a3412',
      ring: '#fb923c'
    }
  },
  {
    id: 'purple-haze',
    name: 'Purple Haze',
    category: 'creative',
    colors: {
      primary: '#a855f7',
      secondary: '#f3e8ff',
      accent: '#c084fc',
      background: '#faf5ff',
      foreground: '#581c87'
    },
    lightModeConfig: {
      background: '#faf5ff',
      foreground: '#581c87',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#a855f7',
      'primary-foreground': '#ffffff',
      secondary: '#f3e8ff',
      'secondary-foreground': '#0f172a',
      muted: '#f5f3ff',
      'muted-foreground': '#64748b',
      accent: '#c084fc',
      'accent-foreground': '#0f172a',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e9d5ff',
      input: '#e9d5ff',
      ring: '#a855f7'
    },
    darkModeConfig: {
      background: '#581c87',
      foreground: '#f3e8ff',
      card: '#7c3aed',
      'card-foreground': '#f8fafc',
      popover: '#7c3aed',
      'popover-foreground': '#f8fafc',
      primary: '#a855f7',
      'primary-foreground': '#ffffff',
      secondary: '#8b5cf6',
      'secondary-foreground': '#f8fafc',
      muted: '#7c3aed',
      'muted-foreground': '#94a3b8',
      accent: '#c084fc',
      'accent-foreground': '#f8fafc',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#8b5cf6',
      input: '#8b5cf6',
      ring: '#a855f7'
    }
  }
];

export const getThemesByCategory = (category: PredefinedTheme['category']) => {
  return PREDEFINED_THEMES.filter(theme => theme.category === category);
};

export const getThemeById = (id: string) => {
  return PREDEFINED_THEMES.find(theme => theme.id === id);
};

export const getAllCategories = (): PredefinedTheme['category'][] => {
  return ['popular', 'nature', 'corporate', 'creative', 'monochrome', 'specialty'];
};